drivers: input: touchscreen: nvt: Properly arrange variables to disable firmware update
* This is needed because Init_BootLoader and Resume_PD is needed
  regardless in nt36xxx_ext_proc while the whole fw_update file
  is ifdef'd with BOOT_UPDATE_FIRMWARE
* Fixes this error when building with BOOT_UPDATE_FIRMWARE disabled:

drivers/input/touchscreen/nvt_touch_d2s/nt36xxx_ext_proc.o: In function `nvt_get_oem_data':
drivers/input/touchscreen/nvt_touch_d2s/nt36xxx_ext_proc.c:624: undefined reference to `Init_BootLoader'
drivers/input/touchscreen/nvt_touch_d2s/nt36xxx_ext_proc.c:630: undefined reference to `Resume_PD'
drivers/input/touchscreen/nvt_touch_d2s/nt36xxx_ext_proc.c:624: undefined reference to `Init_BootLoader'

Change-Id: I9f649ec5e62c6543edf6bcdb65d2765fac6b10b1
Signed-off-by: clarencelol <clarencekuiek@icloud.com>